# Generated by Django 2.2.10 on 2020-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('AG', 'agent'), ('AD', 'admin')], default='AD', max_length=10),
        ),
    ]
