# Generated by Django 2.2.10 on 2020-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200606_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AC', 'active'), ('DS', 'disable')], default='AC', max_length=5),
        ),
    ]
